sudo: false
language: ruby
rvm: '2.6.3'
cache: bundler

script: bundle exec jekyll build

addons:
  apt:
    packages:
    - ncftp

deploy:
  provider: script
  script: >
    ncftpput
    -u $FTP_USERNAME
    -p $FTP_PASSWORD
    -S .tmp
    -R ftp.sinisterstuf.org
    / _site
  on:
    branch: master
  skip_cleanup: true
