sudo: false
language: ruby
rvm: '2.6.3'
cache: bundler

script: bundle exec jekyll build

addons:
  apt:
    packages:
    - ncftp

deploy:
  provider: script
  script: ./_deploy.sh
  on:
    branch: master
  skip_cleanup: true
