sudo: false
language: ruby
rvm: '2.6.3'
cache: bundler

script: bundle exec jekyll build

addons:
  apt:
    packages:
    - ncftp

deploy:
  provider: script
  script: >
    cd _site
    && ncftpput -S .tmp -R
    -u $FTP_USERNAME -p $FTP_PASSWORD
    ftp.sinisterstuf.org / ./
  on:
    branch: master
  skip_cleanup: true
