sudo: false
language: ruby
rvm: '2.6.3'
cache: bundler

script: bundle exec jekyll build

addons:
  apt:
    packages:
    - ncftp

deploy:
  provider: script
  script: >-
    cd _site &&
    ncftpput
    -u $FTP_USERNAME
    -p $FTP_PASSWORD
    -S .tmp 
    -r 3
    -Rz ftp.sinisterstuf.org
    / .
  on:
    branch: master
  skip_cleanup: true
