sudo: false
language: ruby
rvm: '2.6.3'
cache: bundler

# script: bundle exec jekyll build
script: true

deploy:
  provider: script
  script: ./_scripts/cideploy
  on:
    branch: master
  skip_cleanup: true
