sudo: false
language: ruby
rvm: '2.6.3'
cache: bundler

script: bundle exec jekyll build

before_deploy: |
  echo "ftp_username: $FTP_USERNAME" >> _config.yml
  echo "ftp_password: $FTP_PASSWORD" >> _config.yml

deploy:
  provider: script
  script: gem install glynn & glynn
  on:
    branch: master
  skip_cleanup: true
