sudo: false
language: ruby
rvm: '2.6.3'
cache: bundler

script: bundle exec jekyll build

deploy:
  provider: script
  script: |
    #!/usr/bin/env bash
    echo "ftp_username: $FTP_USERNAME" >> _config.yml
    echo "ftp_password: $FTP_PASSWORD" >> _config.yml
    gem install glynn && glynn
  on:
    branch: master
  skip_cleanup: true
