sudo: false
language: ruby
rvm: '2.6.3'
cache: bundler

script: bundle exec jekyll build

deploy:
  provider: script
  # script: ./_scripts/cideploy
  script: "find _site -type f -exec curl -u xxx:psw --ftp-create-dirs -T {} ftp://$FTP_USERNAME:$FTP_PASSWORD@icfbudapest.org:21/{} \;"
  on:
    branch: master
  skip_cleanup: true
